# Generated by Django 4.1.8 on 2023-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('서비스ID', models.CharField(max_length=100)),
                ('서비스명', models.CharField(max_length=500)),
                ('대분류', models.CharField(max_length=100, null=True)),
                ('중분류', models.CharField(max_length=100, null=True)),
                ('소분류', models.CharField(max_length=100, null=True)),
                ('제공기관', models.CharField(max_length=100, null=True)),
                ('제공부서명', models.CharField(max_length=100, null=True)),
                ('시스템명', models.CharField(max_length=500, null=True)),
                ('담당자명', models.CharField(max_length=100, null=True)),
                ('담당자연락처', models.CharField(max_length=100, null=True)),
                ('갱신주기', models.CharField(max_length=100, null=True)),
                ('최종갱신일자', models.DateTimeField(null=True)),
                ('제공사이트', models.CharField(max_length=500, null=True)),
                ('제공형식', models.CharField(max_length=100, null=True)),
                ('서비스설명', models.CharField(max_length=10000, null=True)),
                ('urls', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'seoul_data',
            },
        ),
    ]
