# Generated by Django 4.1.8 on 2023-05-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seouldata',
            options={'ordering': ['서비스명']},
        ),
    ]
