# Generated by Django 4.1.8 on 2023-05-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('INF_ID', models.CharField(max_length=100)),
                ('COL_ENG_NM', models.CharField(max_length=100, null=True)),
                ('COL_KOR_NM', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'seouldata_columns',
            },
        ),
    ]
