# Generated by Django 4.1.8 on 2023-05-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_datacart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datacart',
        ),
    ]
