# Generated by Django 4.1.8 on 2023-05-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_seouldata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seouldata',
            options={},
        ),
    ]
