# Generated by Django 4.1.8 on 2023-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreprocessedImages",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_title", models.TextField(default="a.jpg", null=True)),
                (
                    "image_path",
                    models.FilePathField(
                        default="/home/fffcoder/ocrandnlp/images/a.jpg"
                    ),
                ),
                ("image_context", models.TextField(default="일방통행")),
            ],
            options={
                "db_table": "preprocessed_images",
            },
        ),
    ]
